<?php

namespace AppBundle\Repository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getmesenfqnt($id,$jar){
        $q=$this->getEntityManager()->createQuery("select a from AppBundle:Enfant a
        Join AppBundle:Abonnement ab with a=ab.enfant where a.parent=:parent and ab.jardin=:jardin")
            ->setParameter('parent',$id)->setParameter('jardin',$jar);
        return $query=$q->getResult();
    }
}
