<?php

namespace AppBundle\Repository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchEnfant($search,$id)
    {
        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:Enfant m JOIN m.parent e where  (m.nom like :motcle or m.prenom like :motcle ) and m.parent=:id")
            ->setParameter('motcle','%'.$search.'%')
            ->setParameter('id',$id);
        return $query=$q->getResult();

    }
}
