<?php

namespace AppBundle\Repository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getmessages($id)
    {
        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:Parents p , AppBundle:Messages m where m.parent=p AND m.parent=:id GROUP BY p.id")
            ->setParameter('id',$id);
        return $query=$q->getResult();


    }
    public function getallmess()
    {
        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:Messages m, AppBundle:Parents p where m.parent=p GROUP BY p.id");

        return $query=$q->getResult();


    }

}
