<?php

namespace AppBundle\Repository;

/**
 * PartActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
