<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsername($username)
    {
        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:User m where m.username=:us ")->setParameter("us",$username);

        return $query=$q->getResult();
    }
}
